### ISSUE TITLE
v1.1.1-191 broke autogeneration of i18n.dart

### ISSUE THREAD

**Issue by KorbinianMossandl** [long1eu/flutter_i18n#103] opened 2019-10-01 12:52 UTC
i just upgraded to the latest version and now the i18n file won't update if i make changes to my strings_en.arb

**Comment by noordawod** [comment] 2019-10-01 13:02
There has been a new feature with the release of v1.1.0, could you please read the README and tell me if this fits your usecase?

https://github.com/long1eu/flutter_i18n#3-turning-off-the-plugin-per-project

**Comment by KorbinianMossandl** [comment] 2019-10-01 13:12
sadly not. i am using the plugin on a flutter project. 
Even setting it to enabled did not do the trick. for now only downgrading resolves the issue.

**Comment by noordawod** [comment] 2019-10-01 13:15
This is very strange.

The plugin detects the existance of Flutter in pubspec.yaml, so could you possibly attach it here (you can leave sensitive info out)?

**Comment by noordawod** [comment] 2019-10-01 13:16
Also, what's the highest version number that works for you?

**Comment by KorbinianMossandl** [comment] 2019-10-01 13:21
i just went back to v1.0.6-191 since this was the version i used before the upgrade.

```
name: XXX
description: XXX

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  json_annotation: ^2.3.0
  dio: ^2.1.0
  json_serializable: ^3.0.0
  cookie_jar: ^1.0.0
  sembast: ^1.15.4
  path_provider: ^1.1.0
  encrypt: ^3.1.0
  background_fetch: ^0.2.0
  sentry: ^2.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.13.1
  path_drawing: ^0.4.1
  bubble_tab_indicator: ^0.1.4
  google_maps_flutter: ^0.5.21
  url_launcher: ^5.1.2
  permission_handler: ^3.2.0
  path: ^1.6.2
  pdf_render: ^0.56.0
  webview_flutter: ^0.3.14
  camera: ^0.5.4+2
  file_picker: ^1.4.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.6.3
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - res/assets/icons/
   - res/assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by vysotsky** [comment] 2019-10-01 15:32
I'm facing the same issue

**Comment by noordawod** [comment] 2019-10-01 16:10
Hmm, that's strange. I'll look into it right away. Thanks!

**Comment by noordawod** [comment] 2019-10-01 16:10
Which IDE are you guys using? Name and version. Screenshot of About is great.

**Comment by KorbinianMossandl** [comment] 2019-10-01 16:40
latest android studio:
Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-65-generic

**Comment by bojidartonchev** [comment] 2019-10-01 18:46
Same issue after upgrading to latest version today.

Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by noordawod** [comment] 2019-10-01 21:12
Pushed a fix now #104, awaiting review by the other maintainer.

**Comment by dpedrinha** [comment] 2019-10-02 01:19
Having the same problem here. Same IDE of the others. Just updated both today and the i18n.dart file stopped being generated.
I even tried creating a new project and extracting a string, it immediately crashed and prompted me to fill a bug report. Also there are no .arb files in the res/values folder. 
So it's pretty easy to test the problem.
Thank you for the quick response @noordawod. Any timeline for this fix to be available?
I downloaded your pull request but I don't know how to build and use it locally (noob here).

**Comment by noordawod** [comment] 2019-10-02 06:39
It should be available during the today, thanks guys for the understsanding and sorry for messing it up when initially it was meant to solve many issues :)

Surprisingly, on the IntelliJ IDEA platform, the bug you described above does not happen.

**Comment by noordawod** [comment] 2019-10-02 07:39
Plugin v1.1.2 has been published to JetBrains, awaiting approval. It should be available during the day. Please report back your findings when you install it, thanks!

**Comment by dpedrinha** [comment] 2019-10-02 17:43
Thank you @noordawod for the promptly response and fix.

**Comment by noordawod** [comment] 2019-10-03 10:13
v1.1.2 has landed, please upgrade and check back if it fixes this issue. Thanks!

**Comment by dpedrinha** [comment] 2019-10-03 14:33
Confirmed. i18n.dart is now being generated again.
Thanks.
@noordawod  can you please clarify [this question on SO](https://stackoverflow.com/questions/58193203/what-should-i-use-for-i18n-in-flutter-s-ofcontext-or-s-current?noredirect=1#comment102795820_58193203), please?

**Comment by noordawod** [comment] 2019-10-03 16:23
Great, thanks for checking.
I need to see an example before deducing what the problem may be, could you open a different issue and provide an example?

**Closed as completed by noordawod** 2019-10-03 16:23 UTC
Labels: bug, question, needs input

**Comment by dpedrinha** [comment] 2019-10-03 17:12
Let me check if the problem persists after the update (later) and I'll will work on that if necessary.
But just to clarify, should we use `of(context)` or `current`? Are they the same? What's the difference?

**Comment by noordawod** [comment] 2019-10-03 18:00
I would use `of(context)` always just because it's a good way to uncover bugs in your code, which I'm highly guessing is what happening in your case.

The `current` caches the strings (statically) and I don't recommend using it -- but we merged this pr anyway earlier because users asked for it.
