### ISSUE TITLE
Does not support to generate locale's scriptCode with country code

### ISSUE THREAD

**Issue by AkoWu101** [long1eu/flutter_i18n#39] opened 2019-02-16 17:01 UTC
I create strings_zh_Hant_HK and strings_zh_Hans_CN. 
supportedLocales cannot generate Locale with scriptCode and country code

**Comment by noordawod** [comment] 2019-04-04 12:07
Is this still an issue @KingWu?

If so, please provide:

- Output of `flutter doctor -v`
- IDE version (screenshot of Help > About is best)
- Plugin version

Thanks.

**Comment by noordawod** [comment] 2019-10-01 13:05
Duplicate of #73

**Closed as completed by noordawod** 2019-10-01 13:05 UTC
Labels: needs input
