### ISSUE TITLE
Cannot Undo

### ISSUE THREAD

**Issue by cr33zy** [long1eu/flutter_i18n#90] opened 2019-08-17 08:20 UTC
I get an error message if I try to undo (hit cmd-z) after using translated strings in my .dart-files. It happens every time after the i18n.dart got autogenerated. I thought if there's any way to... maybe generate the i18n.dart manually?

![Cannot_Undo_und_murumate___Applications_MAMP_htdocs_flutter_murumate_murumate__-_____lib_widgets_default_dialogs_dart__murumate_](https://user-images.githubusercontent.com/8394737/63208776-a548ee80-c0d8-11e9-9988-5ec2b90287cd.png)

**Comment by noordawod** [comment] 2019-08-22 17:46
The file is auto-generated, do not edit it. It's written in bold in the beginning of the file. Instead, you should edit the `res/values/*.arb` files.

**Comment by cr33zy** [comment] 2019-08-23 04:44
Oh... Thank you. But I didn't change the auto-generated file but any other file in my lib folder that has a translated string inside itself. So I hit save and the generator gets triggered. After that I try to undo my changes by hitting cmd-z. And then the error message pops up.

**Comment by noordawod** [comment] 2019-08-24 23:24
Hmmm... Could be that the IDE is just doing what it's supposed to do, which is to warn that the auto-generated file will also be reverted back to its earlier version.

**Comment by knaeckeKami** [comment] 2019-08-26 16:09
I hit that bug/issue too, it's pretty annoying; You cannot undo unless you restart the IDE. I could not figure out how to reproduce it, though.

**Comment by noordawod** [comment] 2019-08-27 06:05
That might help but I still think it's an IDE issue...

**Comment by knaeckeKami** [comment] 2019-08-27 09:02
Yes, maybe. I didn't run into this since I upgraded to Android Studio 3.5, so maybe it's already fixed.

**Comment by noordawod** [comment] 2019-08-27 09:53
Closing for now, re-open if needed.

**Closed as completed by noordawod** 2019-08-27 09:53 UTC
Labels: question, wontfix
