### ISSUE TITLE
colliding arb keys with dart language 

### ISSUE THREAD

**Issue by vishna** [long1eu/flutter_i18n#44] opened 2019-02-26 17:37 UTC
if you put as a key in the arb file one of the following values:
- with
- new
- other
- do

the generated class will no longer compile, quick workaround for this would be to put trailing underscore

**Comment by noordawod** [comment] 2019-09-30 11:14
This is a known issue, @vishna.
Would you be able to submit a pr to fix this?

**Comment by vishna** [comment] 2019-10-01 10:30
Unfortunately this is out of my scope - I switched to using VS Code for flutter dev and wrote my own solution: [Android String To Flutter](https://github.com/vishna/as2f) (...which btw [doesn't handle](https://github.com/vishna/as2f/issues/3) this case yet, just using properly named keys 😅 )

...but but I handle this case somewhere else:
https://github.com/vishna/voyager-codegen/blob/master/voyager-codegen/src/main/kotlin/dev/vishna/voyager/codegen/DartSpecialKeys.kt

so you could maybe use that ☝️

**Comment by noordawod** [comment] 2019-10-01 12:02
Duplicate of #63

**Closed as completed by noordawod** 2019-10-01 12:02 UTC
Labels: bug
